# Generated by Django 2.1.7 on 2019-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableone',
            name='password1',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
