# Generated by Django 2.1.7 on 2019-03-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_tableone_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableone',
            name='password1',
        ),
    ]
